-- DDL for ramp-up-pack-service (STAAT retention pack email delivery).
--
-- Schemas:
--   aat_app  — tables OWNED by this service (templates, batches, send log).
--   datamesh — externally populated data products; staat_insight_document is written by
--              DS/datamesh pipelines, this service only ever SELECTs from it.
--
-- In real environments the DBA/pipeline applies this (the app never runs DDL; tests only)
-- and grants the service role: USAGE on both schemas, DML on aat_app tables,
-- SELECT-only on datamesh.staat_insight_document. Idempotent — safe to re-run.

CREATE SCHEMA IF NOT EXISTS aat_app;
CREATE SCHEMA IF NOT EXISTS datamesh;

-- ---------------------------------------------------------------------------
-- aat_app.email_template. subject/body may contain {placeholder} merge fields
-- resolved at send time (caller-supplied merge fields + system fields such as
-- {packCount}, {householdTable}, {partNumber}, {totalParts}, {failureReason}).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aat_app.email_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100)  NOT NULL UNIQUE,   -- stable business key, e.g. FA_DELIVERY_SUCCESS
    name        VARCHAR(200)  NOT NULL,
    description VARCHAR(1000),
    subject     VARCHAR(500)  NOT NULL,
    body        TEXT          NOT NULL,          -- HTML with {placeholders}
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_by  VARCHAR(100)  NOT NULL DEFAULT 'system',
    updated_by  VARCHAR(100)  NOT NULL DEFAULT 'system',
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- datamesh.staat_insight_document (retention packs). Populated EXTERNALLY by
-- DS/datamesh — this service only reads. One fully formed HTML document per
-- ACE relationship, identified to users by the lead client name.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS datamesh.staat_insight_document (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ace_id           VARCHAR(64)  NOT NULL UNIQUE,
    lead_client_name VARCHAR(200) NOT NULL,
    file_name        VARCHAR(255) NOT NULL,      -- e.g. John_Smith_Household.html
    html_content     TEXT         NOT NULL,      -- fully formed HTML from DS
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- aat_app.email_batch — one row per scheduled send request. The scheduler
-- claims due rows (SCHEDULED -> PROCESSING) and runs the same send pipeline
-- as the live API.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aat_app.email_batch (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fa_id            VARCHAR(64),
    field_leader_id  VARCHAR(64),
    recipient_email  VARCHAR(320)  NOT NULL,
    template_id      BIGINT        NOT NULL REFERENCES aat_app.email_template (id),
    fail_template_id BIGINT        NOT NULL REFERENCES aat_app.email_template (id),
    ace_ids          TEXT[]        NOT NULL,
    merge_fields     JSONB         NOT NULL DEFAULT '{}',
    scheduled_at     TIMESTAMPTZ   NOT NULL,
    status           VARCHAR(30)   NOT NULL DEFAULT 'SCHEDULED', -- SCHEDULED|PROCESSING|COMPLETED|FAILED|CANCELLED
    processed_at     TIMESTAMPTZ,
    failure_reason   VARCHAR(2000),
    created_by       VARCHAR(100)  NOT NULL DEFAULT 'system',
    updated_by       VARCHAR(100)  NOT NULL DEFAULT 'system',
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_batch_due ON aat_app.email_batch (status, scheduled_at);

-- ---------------------------------------------------------------------------
-- aat_app.email_log — one row per email PART actually attempted (a logical
-- send splits into parts when attachments exceed the size limit). Stores the
-- merged subject/body for future reference. FAILED rows are retried by the
-- scheduler until 7 days after the first attempt, then marked EXHAUSTED.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aat_app.email_log (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id              BIGINT REFERENCES aat_app.email_batch (id),     -- NULL for live sends
    template_id           BIGINT NOT NULL REFERENCES aat_app.email_template (id),
    fail_template_id      BIGINT REFERENCES aat_app.email_template (id),  -- NULL on failure-notification rows
    fa_id                 VARCHAR(64),
    field_leader_id       VARCHAR(64),
    recipient_email       VARCHAR(320) NOT NULL,
    ace_ids               TEXT[]       NOT NULL,    -- the subset attached to THIS part
    merge_fields          JSONB        NOT NULL DEFAULT '{}',
    merged_subject        VARCHAR(600) NOT NULL,    -- resolved values, for future reference
    merged_body           TEXT         NOT NULL,
    attachment_file_names TEXT[]       NOT NULL DEFAULT '{}',
    part_number           INT          NOT NULL DEFAULT 1,
    total_parts           INT          NOT NULL DEFAULT 1,
    failure_notification  BOOLEAN      NOT NULL DEFAULT FALSE,    -- TRUE for fail-notice emails (never re-notified)
    sme_id                VARCHAR(64),                            -- STAAT message id of last attempt
    status                VARCHAR(30)  NOT NULL DEFAULT 'PENDING', -- PENDING|SENDING|SENT|FAILED|EXHAUSTED
    attempt_count         INT          NOT NULL DEFAULT 0,
    first_attempted_at    TIMESTAMPTZ,                            -- drives the 7-day retry window
    last_attempted_at     TIMESTAMPTZ,
    failure_reason        VARCHAR(2000),
    created_by            VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by            VARCHAR(100) NOT NULL DEFAULT 'system',
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_log_status ON aat_app.email_log (status, first_attempted_at);
CREATE INDEX IF NOT EXISTS idx_email_log_batch  ON aat_app.email_log (batch_id);
