-- Schema for ramp-up-pack-service.
-- Executed on startup when spring.sql.init.mode=always. Idempotent (IF NOT EXISTS),
-- so it is safe to re-run; in production prefer Flyway/Liquibase with mode=never.
CREATE TABLE IF NOT EXISTS ramp_up_pack (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200)  NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(50)   NOT NULL DEFAULT 'DRAFT',
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ramp_up_pack_status ON ramp_up_pack (status);
